id: A0B152020
title: Brief Vajrasattva Visualisation and Mantra Recitation
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:37:53.856924
  last_modified_at: 2022-03-01 05:37:53.856926
