id: A0B152020
title: A Daily Long-Life Practice of Amitāyus
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:37:53.830583
  last_modified_at: 2022-03-01 05:37:53.830586
