id: A0B152020
title: 'Moonlight of Pacifying Amṛta: A Daily Visualization and Recitation for the
  Dispeller of All Samaya Corruptions and Pollutions'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:37:53.876314
  last_modified_at: 2022-03-01 05:37:53.876316
