id: A0B152020
title: 'Fast Track to Happiness and Peace: A Very Brief Meditation and Recitation
  of the Medicine Buddha'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:37:53.868719
  last_modified_at: 2022-03-01 05:37:53.868722
