id: A0B152020
title: 'The Sublime Path to Immortality: The Quintessence of Profoundly Secret Pith
  Instructions on Attaining Vajra Longevity'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:37:53.907568
  last_modified_at: 2022-03-01 05:37:53.907570
