id: A0B152020
title: 'The Heart of Wish-Fulfilling Jewels: A Brief Practice for Paying Homage and
  Making Offerings to the Buddha together with his retinue of Arhats'
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:37:53.902465
  last_modified_at: 2022-03-01 05:37:53.902468
