id: A0B152020
title: 'The Treasury of Blessings: A Practice of Buddha Śākyamuni'
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:37:53.913464
  last_modified_at: 2022-03-01 05:37:53.913469
