id: A0B152020
title: 'The Concentrated Essence: A Sādhana of Yeshe Tsogyal'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:37:53.894945
  last_modified_at: 2022-03-01 05:37:53.894948
