id: A0B152020
title: Light from the Wisdom Sun
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:37:53.874042
  last_modified_at: 2022-03-01 05:37:53.874045
