id: A0B152020
title: A Means to Pacify the Fear of Natural Disasters
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:37:53.837946
  last_modified_at: 2022-03-01 05:37:53.837948
