id: A0B152020
title: Daily Practice of Mañjuśrī Yamāntaka
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:37:53.864261
  last_modified_at: 2022-03-01 05:37:53.864263
