id: A0B152020
title: 'Inlaid Jewels: Addenda to the ''Neck-Pouch Dagger’ (Purba Gulkhukma) Cycle'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:37:53.872912
  last_modified_at: 2022-03-01 05:37:53.872915
