id: A0B152020
title: A Brief Visualization and Recitation of the Great Mother Praj침캐p캐ramit캐
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:37:53.825811
  last_modified_at: 2022-03-01 05:37:53.825820
