id: A0B152020
title: Concise Daily Practice of Vajrasattva
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:37:53.857917
  last_modified_at: 2022-03-01 05:37:53.857920
