id: A0B152020
title: A Brief Practice of Paying Homage and Making Offerings to the Sixteen Elders
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:37:53.822432
  last_modified_at: 2022-03-01 05:37:53.822454
