id: A0B152020
title: The Single-Page Practice of the Guru of Great Bliss
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:37:53.906494
  last_modified_at: 2022-03-01 05:37:53.906496
