id: A0B152020
title: 'The Falling Rain of Blessings: A Brief Daily Practice of the Wealth Deity
  White Jambhala'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:37:53.900258
  last_modified_at: 2022-03-01 05:37:53.900261
