id: A0B152020
title: Visualization and Mantra Recitation of the Great Compassionate One
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:37:53.917089
  last_modified_at: 2022-03-01 05:37:53.917091
