id: A0B152020
title: Condensed Daily Practice of The Heart Essence of the Sublime Lady of Immortality
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:37:53.860068
  last_modified_at: 2022-03-01 05:37:53.860071
