id: A0B152020
title: 'Accomplishing All Activity: A Daily Practice of the Great and Glorious Dorje
  Drolö'
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:37:53.855808
  last_modified_at: 2022-03-01 05:37:53.855811
