id: A0B152020
title: Sādhana of Bhaiṣajya Guru (Medicine Buddha)
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:37:53.881617
  last_modified_at: 2022-03-01 05:37:53.881620
