id: A0B152020
title: 'The Cintāmaṇi (Wish-Fulfilling Jewel) Instruction: A Sādhana of the Glorious
  Vajrasattva, a Method of Purification and Accomplishment for Both Self and Others'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:37:53.893560
  last_modified_at: 2022-03-01 05:37:53.893563
