id: A0B152020
title: A Concise Meditation and Mantra Recitation of Sarasvatī from the Heart Essence
  of the Ḍākinī of Suchness (Chönyi Khandrö Tuktik)
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:37:53.827353
  last_modified_at: 2022-03-01 05:37:53.827357
