id: A0B152020
title: Concise White Tārā Sādhana
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:37:53.858945
  last_modified_at: 2022-03-01 05:37:53.858948
