id: A0B152020
title: 'Highway of the Great Yoga: A Daily Practice for the Peaceful and Wrathful
  Deities of the Self-Liberated Wisdom Mind'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:37:53.869944
  last_modified_at: 2022-03-01 05:37:53.869947
