id: A0B152020
title: A Daily Practice of Lama Sangdü
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:37:53.832944
  last_modified_at: 2022-03-01 05:37:53.832948
