id: A0B152020
title: 'Swift Bestowal of Blessings: A Peaceful Sādhana of Mañjuśrī'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:37:53.878896
  last_modified_at: 2022-03-01 05:37:53.878899
