id: A0B152020
title: 'The Sādhana of the Five Self-Arisen Noble Brothers: An Instruction in the
  Union of Generation and Completion'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:37:53.910150
  last_modified_at: 2022-03-01 05:37:53.910154
