id: A0B152020
title: Visualization and Recitation of the Six-Syllable Mantra of Avalokiteśvara
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:37:53.918436
  last_modified_at: 2022-03-01 05:37:53.918439
