id: A0B152020
title: 'The Accomplishment of Supreme Enlightened Activity: A Recitation Manual for
  The Vajrakīla Root Tantra Section'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:37:53.885139
  last_modified_at: 2022-03-01 05:37:53.885142
